### ISSUE TITLE
garbage collector error in c# applciation

### ISSUE THREAD

**Issue by ffbboy30** [xioTechnologies/x-IMU-GUI#1]
Hello,
Still have problem with the use of the x-IMU3 dll in a c# application.
One I try to use it I've an error with the callbackOnCollectedDelegate that come at random time.
See the explanation
[(https://learn.microsoft.com/en-us/dotnet/framework/debug-trace-profile/callbackoncollecteddelegate-mda)]
From the original sample I only add a global variable I print on the console  in a loop.
Could you explain how to manage the garbage collector in your sample.

Thanks for you help

**Comment by xioTechnologies** [comment]
This repository is for the [x-IMU3 GUI](https://github.com/xioTechnologies/x-IMU-GUI).  The x-IMU GUI is not compatible with the x-IMU3.  If you have an issue with the [x-IMU3 Software](https://github.com/xioTechnologies/x-IMU3-Software) then please open an issue in that repository.
